# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OVsWHIIM_MQ9P4ibZBOkpFKU9ZZE3IQ4
"""

import streamlit as st
import numpy as np
import joblib

# ---- Load model and scaler ----
scaler = joblib.load("scaler.pkl")
model = joblib.load("knn_model.pkl")

# ---- Streamlit App ----
st.title("🩺 Health Prediction App (KNN Model)")

st.write("Enter the health details below to get a prediction:")

# Example: features from Breast Cancer dataset (adjust according to your dataset)
# If your dataset has different features, update this section
mean_radius = st.number_input("Mean Radius", min_value=0.0, step=0.1)
mean_texture = st.number_input("Mean Texture", min_value=0.0, step=0.1)
mean_perimeter = st.number_input("Mean Perimeter", min_value=0.0, step=0.1)
mean_area = st.number_input("Mean Area", min_value=0.0, step=0.1)
mean_smoothness = st.number_input("Mean Smoothness", min_value=0.0, step=0.001)

# Collect inputs
user_input = [mean_radius, mean_texture, mean_perimeter, mean_area, mean_smoothness]

if st.button("Predict"):
    # Scale input
    user_scaled = scaler.transform([user_input])

    # Predict
    prediction = model.predict(user_scaled)[0]

    # Show result
    if prediction == 0:
        st.error("⚠️ The model predicts: Malignant (cancerous)")
    else:
        st.success("✅ The model predicts: Benign (not cancerous)")